export default [
  { name: '数码手机', icon: 'icon-shumashouji' },
  { name: '游戏', icon: 'icon-94' },
  { name: '住房', icon: 'icon-zhufang' },
  { name: '日用品', icon: 'icon-riyongpin' },
  { name: '数码', icon: 'icon-shuma' },
  { name: 'steam', icon: 'icon-steam' },
  { name: '超市', icon: 'icon-chaoshi' },
  { name: '淘宝', icon: 'icon-taobao' },
  { name: '水果', icon: 'icon-shuiguo' },
  { name: '餐饮', icon: 'icon-icon-' },
  { name: '银行卡', icon: 'icon-shuaqiaqiapianyinhangqia' },
  { name: '缴费', icon: 'icon-weibiaoti--' },
  { name: '支付宝 账户', icon: 'icon-zhifubaozhanghu' },
  { name: '工资', icon: 'icon-gongzi' },
  { name: '设 置', icon: 'icon-shezhi' },
  { name: '医疗', icon: 'icon-yiliao' },
  { name: '医疗', icon: 'icon-yiliao1' },
  { name: 'origin', icon: 'icon-origin' },
];
